version: '3.7'

services:

  postgresql:
    image: postgres:latest
    container_name: postgresql
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    
volumes:
  dbdata: